-- Права необходимые для компиляции PFLB_DATASAN
-- v$session используется в процедуре PFLB_UPD_ERR_HAND
GRANT SELECT ON v_$session TO FULL_SCHEMA_TEST
/
GRANT SELECT ON v_$mystat TO FULL_SCHEMA_TEST
/
GRANT SELECT ON v_$statname TO FULL_SCHEMA_TEST
/
GRANT CREATE PROCEDURE TO SMOKE_TEST
/
GRANT CREATE JOB TO SMOKE_TEST
/
GRANT EXECUTE ON sys.dbms_job TO SMOKE_TEST
/

GRANT SELECT ANY DICTIONARY TO SMOKE_TEST
/

GRANT CREATE ANY TABLE TO SMOKE_TEST
/
GRANT ALTER ANY TABLE TO SMOKE_TEST
/
GRANT DROP ANY TABLE TO SMOKE_TEST
/

GRANT CREATE ANY INDEX TO SMOKE_TEST
/
GRANT DROP ANY INDEX TO SMOKE_TEST
/
