create or replace package PFLB_DATASAN as
function PFLB_GET_UNIQ_COL(towner_name varchar2, ttable_name varchar2, idtype in out varchar2) return varchar2;
TYPE id_row IS RECORD (id number);
TYPE id_table IS TABLE OF PFLB_DATASAN.id_row;
TYPE id_row_c IS RECORD (id varchar2(255));
TYPE id_table_c IS TABLE OF PFLB_DATASAN.id_row_c;
function PFLB_GET_KEY_COLUMN(towner_name varchar2, ttable_name varchar2, idtype in out varchar2 ) return varchar2;
function PFLB_GET_IDENTITY_COLUMN(towner_name varchar2, ttable_name varchar2) return varchar2;
function PFLB_GET_TABLE_NAME(tquery varchar2) return varchar2;
PROCEDURE PFLB_GET_INDEXES(towner_name varchar2, ttable_name varchar2, tcolumn_name varchar2);
PROCEDURE PFLB_GENERATE_UPDATE(insql in out varchar2, distOwnerName  varchar2, distTableName  varchar2, encodeFunctionName varchar2, encodeMethod varchar2);
FUNCTION PFLB_GET_MAX_PROCESSED_ID (tquery varchar2) RETURN NUMBER;
FUNCTION PFLB_GET_MAX_PROC_ID_c (tquery varchar2) RETURN VARCHAR2;
PROCEDURE PFLB_UPDATE_JOB(upstr varchar2,owner_n varchar2, table_n varchar2,dictflag integer);
PROCEDURE PFLB_UPD_PROC_INFO (tquery varchar2, max_ids in out NUMBER);
PROCEDURE PFLB_UPD_PROC_INFO_C (tquery varchar2, max_ids in out varchar2);
PROCEDURE PFLB_GET_OR_CR_KEY_COL(towner_name varchar2, ttable_name varchar2, tkey_column in out varchar2, sim integer, idctyp in out varchar2);
PROCEDURE PFLB_DROP_COL_IDX(towner_name varchar2, ttable_name varchar2);
function PFLB_COMBINE_SQL(tmain_part varchar2, twhere_clause varchar2) return varchar2;
PROCEDURE PFLB_ENABLE_INDEXES;
PROCEDURE PFLB_DISABLE_INDEXES_API;
PROCEDURE PFLB_DISABLE_INDEXES(table_ownerName varchar2,table_tableName varchar2);
PROCEDURE PFLB_EXEC_BY_RANGES(ownerName varchar2, TableName varchar2, where_clause varchar2, tquery varchar2, trows_per_tran number, threads integer, mthreads integer, priory integer, tk_column varchar2, sim integer);
PROCEDURE PFLB_EXEC_BY_RANGES_C(ownerName varchar2, TableName varchar2, where_clause varchar2, tquery varchar2, trows_per_tran number, threads integer, mthreads integer, priory integer, tk_column varchar2, sim integer);
PROCEDURE PFLB_EXEC_BY_RANG_STHR(ownerName varchar2, TableName varchar2, where_clause varchar2, tquery varchar2, trows_per_tran number, threads integer, mthreads integer, priory integer, tk_column varchar2, sim integer);
PROCEDURE PFLB_EXEC_BY_RANG_STHR_C(ownerName varchar2, TableName varchar2, where_clause varchar2, tquery varchar2, trows_per_tran number, threads integer, mthreads integer, priory integer, tk_column varchar2, sim integer);
PROCEDURE PFLB_GEN_AND_EXEC_UPD_DE(lickey varchar2, encodeFunctionName varchar2, encodeMethod varchar2, rows_per_update number, threads integer, mthreads integer, sim integer, priory integer,viewCont_ownerName varchar2,distTableName varchar2, where_clause varchar2);
PROCEDURE PFLB_GEN_AND_EXEC_UPD_AS(lickey varchar2, encodeFunctionName varchar2, encodeMethod varchar2, rows_per_update number, threads integer, mthreads integer, sim integer,priory integer,viewCont_ownerName varchar2,distTableName varchar2, where_clause varchar2);
PROCEDURE PFLB_PROCESS_DATA_TYPE(lickey varchar2, encodeMethod varchar2, threads integer, rows_per_update number, sim integer,thread_per_dechannel number,de_channel number,as_channel number);
PROCEDURE PFLB_WRITE_LOGS(logstring varchar2);
PROCEDURE PFLB_DROP_ALL_COL_IDX(lickey varchar2);
PROCEDURE PFLB_ENABLE_TRIGGERS (towner varchar2, ttablename varchar2);
PROCEDURE PFLB_DISABLE_TRIGGERS(towner varchar2, ttablename varchar2);
FUNCTION PFLB_FIX_UPD(upstr varchar2) return varchar2;
PROCEDURE PFLB_ENABLE_INDEX_JOB(index_ownerName varchar2,index_tableName varchar2,index_indexName varchar2,threads integer);
PROCEDURE PFLB_INDEX_SCHED(threads_am number);
procedure pflb_dict_fill(owner_n varchar2,table_n varchar2);
PROCEDURE PFLB_UPD_ERR_HAND(upstr varchar2,owner_n varchar2, table_n varchar2, SQL_ERR integer, ssid integer);
PROCEDURE PFLB_CHECK_DEP_ST;
function PFLB_GET_BD_VER return integer;
function PFLB_GET_DS_VER return varchar2;
PROCEDURE PFLB_SLEEP(secs number);
PROCEDURE PFLB_DICT_FILL_ALL;
end PFLB_DATASAN;