CREATE TABLE PFLBP_DICT_SEARCH_RULES (ID NUMBER NULL, RULE VARCHAR2(4000) NULL, DESCRIPTION VARCHAR2(4000) NULL)
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE PFLBP_REGEXP_SEARCH_RULES (ID NUMBER NULL, RULE VARCHAR2(4000) NULL, DESCRIPTION VARCHAR2(4000) NULL, VALIDATEMETHOD VARCHAR2(4000) NULL)
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE PFLBP_ACTIVE_JOBS("JOB_ID" NUMBER, "UPSTRING" VARCHAR2(1999 BYTE), "SID" NUMBER(*,0), "PRIORITY" NUMBER)
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE "PFLBP_ACTIVE_STATUS"( "UPSTRING" VARCHAR2(1999 BYTE))
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE "PFLBP_LOGS"("ID" NUMBER(*,0), "LSTR" VARCHAR2(4000 BYTE), "LDATE" TIMESTAMP (6))
/ --HARDCODE FOR DEPLOYMENT
CREATE SEQUENCE PFLBP_logs_seq START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE
/ --HARDCODE FOR DEPLOYMENT
-- используется ли?
CREATE SEQUENCE prof_id_seq START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE "PFLBP_NPROFILED_COLUMNS" (	
    OWNER        VARCHAR2(255 BYTE), 
	  TABLE_NAME   VARCHAR2(255 BYTE), 
	  COLUMN_NAME  VARCHAR2(255 BYTE)
)/ --HARDCODE FOR DEPLOYMENT

CREATE TABLE PROFILE (
  ID NUMBER DEFAULT prof_id_seq.nextval NOT NULL,
  OWNER VARCHAR2(100) NULL,
  TABLE_NAME VARCHAR2(100) NULL,
  COLUMN_NAME VARCHAR2(100) NULL,
  "METHOD" VARCHAR2(50) NULL,
  PERCENTS VARCHAR2(50) NULL,
  DESCRIPTION VARCHAR2(500) NULL,
  CONSTRAINT PFLBP_prof_id_nnull CHECK ("ID" IS NOT NULL),
  CONSTRAINT PFLBP_prof_id_pk PRIMARY KEY (ID)
)/ --HARDCODE FOR DEPLOYMENT

CREATE TABLE PROFILE_SUMMARY (
  ID NUMBER DEFAULT prof_id_seq.nextval NOT NULL,
  OWNER VARCHAR2(100) NULL,
  TABLE_NAME VARCHAR2(100) NULL,
  COLUMN_NAME VARCHAR2(100) NULL,
  COMB_METHOD VARCHAR2(100) NULL,
  METHOD_DESC VARCHAR2(50) NULL,
  CONSTRAINT PFLBP_profs_id_nnull CHECK ("ID" IS NOT NULL),
  CONSTRAINT PFLBP_profs_id_pk PRIMARY KEY (ID)
)/ --HARDCODE FOR DEPLOYMENT

CREATE OR REPLACE VIEW PROFILE_VIEW AS
SELECT atc.owner, atc.table_name, atc.column_name
FROM all_tab_columns atc
JOIN all_tables at ON atc.owner = at.owner AND atc.table_name = at.table_name
WHERE atc.owner NOT IN (
    'SYS', 'SYSTEM', 'OUTLN', 'AUDSYS', 'DBSNMP', 'APPQOSSYS', 
    'GSMADMIN_INTERNAL', 'DBSFWUSER', 'XDB', 'WMSYS', 'OJVMSYS', 
    'CTXSYS', 'ORDSYS', 'ORDDATA', 'MDSYS', 'OLAPSYS', 'LBACSYS', 
    'DVSYS', 'PFLBUSER'
)
AND atc.data_type LIKE '%CHAR%'
ORDER BY atc.owner, atc.table_name
/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE last_profiled_table (
    owner       VARCHAR2(100),
    table_name  VARCHAR2(100),
    column_name VARCHAR2(100)
)/ --HARDCODE FOR DEPLOYMENT

CREATE TABLE PROGRESS_LOG (	
  "LOG_TIME" TIMESTAMP (6) NOT NULL ENABLE, 
	"DONE_CNT" NUMBER NOT NULL ENABLE, 
	"TOTAL_CNT" NUMBER NOT NULL ENABLE, 
	"PCT" NUMBER(5,2) NOT NULL ENABLE, 
	"ACTIVE_JOBS" NUMBER, 
	"ELAPSED_TIME" INTERVAL DAY (3) TO SECOND (6), 
	"PROFILE_CNT" NUMBER, 
	"ETA" INTERVAL DAY (3) TO SECOND (6),
  "WORKERS_COUNT" NUMBER
)/ --HARDCODE FOR DEPLOYMENT

CREATE TABLE PFLBP_WORKER_TRACKING(
  "WORKER_ID" NUMBER, 
	"START_TIME" TIMESTAMP, 
	"END_TIME" TIMESTAMP, 
	"STATUS" VARCHAR2(20 BYTE), 
	 PRIMARY KEY ("WORKER_ID")
)/ --HARDCODE FOR DEPLOYMENT
CREATE TABLE profile_table_with_nums(
  OWNER VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	TABLE_NAME VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	COLUMN_NAME VARCHAR2(128 BYTE) NOT NULL ENABLE, 
	NUM_ROWS NUMBER
)/ --HARDCODE FOR DEPLOYMENT

CREATE OR REPLACE VIEW PROFILE_VIEW_WITH_NUMS AS
SELECT atc.owner, atc.table_name, atc.column_name, at.num_rows
FROM all_tab_columns atc
JOIN all_tables at ON atc.owner = at.owner AND atc.table_name = at.table_name
WHERE atc.owner NOT IN (
    'SYS', 'SYSTEM', 'OUTLN', 'AUDSYS', 'DBSNMP', 'APPQOSSYS', 
    'GSMADMIN_INTERNAL', 'DBSFWUSER', 'XDB', 'WMSYS', 'OJVMSYS', 
    'CTXSYS', 'ORDSYS', 'ORDDATA', 'MDSYS', 'OLAPSYS', 'LBACSYS', 
    'DVSYS', 'PFLBUSER'
)
AND atc.data_type LIKE '%CHAR%'/ --HARDCODE FOR DEPLOYMENT

CREATE OR REPLACE VIEW PROFILE_VIEW_SORTED_BY_ROWS_COUNT AS 
SELECT OWNER, TABLE_NAME, COLUMN_NAME, NUM_ROWS
FROM   profile_table_with_nums
ORDER  BY num_rows DESC/ --HARDCODE FOR DEPLOYMENT


CREATE OR REPLACE VIEW PROFILE_VIEW_BY_ROWS_ASC AS 
SELECT owner, table_name, column_name, ROW_NUMBER() OVER (ORDER BY num_rows ASC) AS idx
FROM profile_view_sorted_by_rows_count/ --HARDCODE FOR DEPLOYMENT


create or replace procedure prepare_tables as
begin
    EXECUTE IMMEDIATE 'DROP TABLE profile_table_with_nums';
    EXECUTE IMMEDIATE 'CREATE TABLE profile_table_with_nums as SELECT * FROM profile_view_with_nums';
    
    EXECUTE IMMEDIATE 'update profile_table_with_nums set num_rows = 1 where num_rows is null';
    EXECUTE IMMEDIATE 'delete from profile_table_with_nums where num_rows = 0';
    
    EXECUTE IMMEDIATE 'CREATE INDEX idx_num_rows ON profile_table_with_nums(num_rows)';
end;/ --HARDCODE FOR DEPLOYMENT

/
